[package]
name = "piratepaperwallet"
version = "0.1.0"
authors = ["mrlynch"]
edition = "2018"

[dependencies]
clap = "2.33.3"
piratepaperlib = { path = "../lib" }
json = "0.12.4"
printpdf = "0.4.0"
hex = "0.4.3"
