[package]
name = "qtlib"
version = "0.1.0"
authors = ["mrlynch"]
edition = "2018"

[lib]
name = "piratepaperrust"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.100"
piratepaperlib = { path = "../lib" }